<a href="https://colab.research.google.com/github/Hyenni/practice_tensorflow/blob/master/tensorflow_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Tensorflow

###An open source software library that uses data flow graphs to compute numbers.


##**Tensorflow  movement**

1) Draw graph using tensorflow operation

* define nodes

2) Data feeding & graph operation running

* sess.run(node)

3) Variable update & return value

* print(output of sess.run(node))

In [1]:
import tensorflow as tf
tf.__version__

'1.12.0'

In [2]:
hello = tf.constant("Hello, TensorFlow!")
sess = tf.Session()
print(sess.run(hello))

b'Hello, TensorFlow!'


In [3]:
#placeholder definition

node1 = tf.placeholder(tf.float32)
node2 = tf.placeholder(tf.float32)

#operation definition

node3 = node1 + node2

#session definition

sess = tf.Session()

#If you do not enter the data, an error will occur. <InvalidArgumentError>
print(sess.run(node3))

InvalidArgumentError: ignored

##**tf.placeholder**

* Users can enter input values.

* Use the 'feed_dict' argument to get the input in the form of a dictionary. 

In [4]:
#run session with fed data
#single value feeding

print(sess.run(node3, feed_dict={node1: 1.6, node2: 4}))

#liest value feeding

print(sess.run(node3, feed_dict={node1: [3,5], node2: [4,6]}))

5.6
[ 7. 11.]


##**tensorflow basic function**

###1) tf.reduce => A function that reduces dimension through various operations.

* tf.reduce_sum => a sum of list value.

* tf.reduce_mean => a mean of list value.

In [5]:
import numpy as np

x = [[1.,2.,3.],[4.,5.,6.]]

sess = tf.Session()

#numpy array

x = np.array(x)

print("x : ", x)
print("x.shape : ", x.shape)
print("reduce_sum : ", sess.run(tf.reduce_sum(x)))
print("reduce_sum.shape : ", sess.run(tf.reduce_sum(x)).shape)

x :  [[1. 2. 3.]
 [4. 5. 6.]]
x.shape :  (2, 3)
reduce_sum :  21.0
reduce_sum.shape :  ()


In [6]:
print("x : ", x)

#total mean value
print(sess.run(tf.reduce_mean(x)))
print("shape : ", sess.run(tf.reduce_mean(x)).shape)

#standard: axis=0 each column
print(sess.run(tf.reduce_mean(x, axis=0)))
print("reduce(axis=0).shape : ", sess.run(tf.reduce_mean(x, axis=0)).shape)

#standard: axis=1 each row
print(sess.run(tf.reduce_mean(x, axis=1)))
print("reduce(axis=0).shape : ", sess.run(tf.reduce_mean(x, axis=1)).shape)

x :  [[1. 2. 3.]
 [4. 5. 6.]]
3.5
shape :  ()
[2.5 3.5 4.5]
reduce(axis=0).shape :  (3,)
[2. 5.]
reduce(axis=0).shape :  (2,)


### 2) tf.matmul => a matrix product


In [7]:
#2*3 matrix
X = [[1.,2.,3.],[1.,2.,3]]

#3*1 matrix
W = [[1.],[1.],[1]]

#2*3 * 3*1 => 2*1 matrix
expr = tf.matmul(X,W)
print(sess.run(expr))

[[6.]
 [6.]]


###3) tf.cast => data type conversion

In [8]:
x = tf.constant([1.2, 3.1], dtype=tf.float32)
print(x)

#to int data type
x = tf.cast(x, tf.int32)
print(x)

Tensor("Const_1:0", shape=(2,), dtype=float32)
Tensor("Cast:0", shape=(2,), dtype=int32)


###4) tf.stack

In [9]:
x = tf.constant([1, 4])
y = tf.constant([2, 5])
z = tf.constant([3, 6])

#direction: column
print(sess.run(tf.stack([x,y,z])))
print(tf.stack([x, y, z]))

#direction: row
print(sess.run(tf.stack([x,y,z], axis=1)))
print(tf.stack([x, y, z], axis=1))

[[1 4]
 [2 5]
 [3 6]]
Tensor("stack_1:0", shape=(3, 2), dtype=int32)
[[1 2 3]
 [4 5 6]]
Tensor("stack_3:0", shape=(2, 3), dtype=int32)
